rvm:
- 2.6.0
bundler_args: "--without debug development"
cache: bundler
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
before_script:
- export SECRET_KEY_BASE="$(bundle exec rake secret)"
- cp .sample.env .env
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - SECRET_KEY_BASE="$(bundle exec rake secret)"
services:
  - postgresql
  - xvfb
script: xvfb-run bundle exec rake

