rvm:
- 2.4.2
bundler_args: "--without debug development"
cache: bundler
before_script:
- cp .sample.env .env
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env: SECRET_KEY_BASE="$(bundle exec rake secret)"
